### ISSUE TITLE
Highlight may look funny when parts of symbols aren't actually connected

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#109]
Just something that came up in this animation, with split up fields that are the same field. Looks a bit weird. It's not important at this moment, since it's not animated and I can just delete those inner fields so only one symbol in that field... but just something to be aware of, as I'm sure it will pop up.

![highlight](https://cloud.githubusercontent.com/assets/8481323/17679846/96730cd6-62fa-11e6-8985-f34ad305d385.png)

**Comment by ivyreese** [comment]
Nothing I can do about that.
