### ISSUE TITLE
Control dividers don't work when properly when in portrait mode

### ISSUE THREAD

**Issue by Nathanoid** [cdig/svg-activity-components#119]
Dividers make a mess of things when the control panel moves to the bottom of the window. 

![screen shot 2016-08-23 at 7 34 29 am](https://cloud.githubusercontent.com/assets/8481272/17893855/767a3a84-6904-11e6-9979-7989aa34fab4.png)

I'm thinking either make them little vertical slices or just removing them altogether somehow.

**Comment by ivyreese** [comment]
Yeah.. this is a tricky one. I'll just hide them for now.

**Comment by ivyreese** [comment]
Fixed.
