### ISSUE TITLE
Safari is weird with animations that have a slider....

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#127]
It seems there are some weird things that happen to the animations with the slider. I don't know if it's due to the slider or just having a control at all (as I only have used slider). All the other animations in the module are fine, the cylinders, the arrows, etc, without any controls.

Safari Version 9.1.2 (11601.7.7)

Here are some examples:

Cylinder extend color glitchy (cylinder streaking)
![cylinder-extend-in-safari](https://cloud.githubusercontent.com/assets/8481323/18141195/c62488ce-6f75-11e6-9196-6e03b79d18df.png)
Flow arrow streaks
![flow-arrow-streaks](https://cloud.githubusercontent.com/assets/8481323/18141194/c623a490-6f75-11e6-9453-d4859ebfd1f1.png)
Slider streaks
![slider-streaks](https://cloud.githubusercontent.com/assets/8481323/18141196/c6261c02-6f75-11e6-8202-430457d6a1e8.png)

**Comment by crystalrubik** [comment]
Update: The issues change with the browser width, and as a smaller width fixed those animations, it caused streaks on a pump in a looping schematic animation. Different widths seem to cause different problems...

**Comment by ivyreese** [comment]
This is due to Safari not properly clearing its buffers. Pretty much all graphical systems (Mac OS, Safari, Chrome, video games, Windows, Android, CSS, etc) will have this happen from time to time. Nothing we can do.
