### ISSUE TITLE
Race conditions in svg-activity-root.coffee

### ISSUE THREAD

**Issue by ivyreese** [cdig/svg-activity-components#13]
Two issues in one!

Firstly, [line 46](https://github.com/cdig/svg-activity-components/blob/v2/source/core/svg-activity-root.coffee#L46) causes errors because, sometimes, contentDocument is null. Whoever calls `setupDocument` is probably running too soon, and may need to have "DOMContentLoaded" added to their `Take`s.

Secondly, the `svg-activity-root.coffee` file makes some calls to DOM APIs via PureDOM. But, it doesn't properly wait until the DOM is loaded — again, with `Take "DOMContentLoaded"`. It's important that ANY code that touches the DOM either wait until the document is fully loaded, or be written very carefully to handle nulls and nondeterminism. Please call me out if you ever see any of my code that exhibits such vulnerabilities.

**Comment by theseanzo** [comment]
Shouldn't PureDom be required to take `DOMContentLoaded`?

**Comment by ivyreese** [comment]
Very good question!

PureDom is pure — it only operates on DOM elements that you pass to it. PureDom makes no assumptions about the state of the world. Eg: the DOM nodes you pass in might not be attached to the window. So there's no reason PureDom needs to wait for DOMContentLoaded, and there are some cases where you'll want to use PureDOM before DOMContentLoaded fires.

Rule of thumb: If you use `document` in your code, you should make sure you `Take "DOMContentLoaded"`, because that event means "the `document` is ready".

I will add this to the PureDOM docs, because it's not at all obvious without reading and understanding the PureDOM source.
