### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/svg-activity-components#15]
This is a reminder that we always have to provide a way for users to zoom in on animations.

**Comment by ivyreese** [comment]
Basically, we're looking for a redesign/reimplementation of StageNav from Flash. When you're ready Sean, let's talk about what that would entail, and what features will need to be included (and what BS we can cut out — the Flash version definitely had some nonsense to it)

**Comment by theseanzo** [comment]
This is in there now as long as there is a mainStage!
