### ISSUE TITLE
Settings button click handling is weird

### ISSUE THREAD

**Issue by ivyreese** [cdig/svg-activity-components#154]
Crystal: Sometimes when you click settings and leave settings, it will continue to pop up with each click.

Mark: Why when I put my mouse over the upper LH SETTINGS icon and click nothing happens, but if I click anywhere on the screen the SETTINGS menu shows up? Shouldn't it show up when I click on it?

Might be more likely to happen in chrome

Repro: https://www.lunchboxsessions.com/materials/fixed-variable-displacement-pumps/pressure-compensated-pump-adjustments-simulation

1) In Chrome..
2) Clicks settings button
3) Click red close button
4) Adjust Compensator Setting

When you release the mouse after adjusting the compensator, the Settings window opens again.

**Comment by iMcKelvie** [comment]
Can confirm this is still occurring on my new P O Check Valves animation.
