### ISSUE TITLE
Severe: PageScrollWatcher triggering duplicate Make calls

### ISSUE THREAD

**Issue by Nathanoid** [cdig/svg-activity-components#19]
When I exit a page in a module (scroll down to the next cd-page), then return to the same page it appears to try to add a new instance of the svg animation. The animating goes haywire, in this particular animation I think the defPos variables are getting reset, and the console says: 

Uncaught Error: You may not Make() the same name twice: balanced-vane-pump-1

Where 'balanced-vane-pump-1' is the name of my animation.

**Comment by ivyreese** [comment]
This issue is more serious than the others, since it's breaking things in a user-visible way. We'll need a fix for this before we can start deploying v2 modules and animations.

**Comment by ivyreese** [comment]
:cake:
