### ISSUE TITLE
Confusing documentation with symbol registration argument order.

### ISSUE THREAD

**Issue by Nathanoid** [cdig/svg-activity-components#20]
The information in these two examples conflict in the document.

Under Symbol Definition it says: 
`activity.registerInstance("gauge1", "gauge")`

Under Registering Symbols with Instances it says:
`activity.registerInstance("symbolDefinitionName", "instanceName")`

The order of the arguments in the first example looks backwards to the second example.

**Comment by theseanzo** [comment]
Stupid stupid stupid stupid stupid me.
