### ISSUE TITLE
Is it legal to register an element with multiple symbols?

### ISSUE THREAD

**Issue by ivyreese** [cdig/svg-activity-components#21]
`activity.registerInstance("myElement", "firstSymbol")`

`activity.registerInstance("myElement", "secondSymbol")`

Is there ever a case where you'd legally want to do this? If not, it should probably throw an error.

**Comment by theseanzo** [comment]
No, it is not. It'll just take the second symbol. I'll fix this.

**Comment by theseanzo** [comment]
Resolved in the activity starter
