### ISSUE TITLE
Return of the Masking Issue

### ISSUE THREAD

**Issue by ivyreese** [cdig/svg-activity-components#27]
Crystal said:

Having same masking issue as we had in the previous SVG version. You had removed this line `mask.setAttribute("height", "100%")` in `svg-mask.coffee`. Uncommenting it doesn't appear to work this time. 

![mask](https://cloud.githubusercontent.com/assets/8481323/11702370/5f008bce-9e93-11e5-9625-9c411b09168b.png)

**Comment by theseanzo** [comment]
Gotta place the masks on the main stage.
