### ISSUE TITLE
scope.style.visible(isVisible) does not change the visibility of children of scope

### ISSUE THREAD

**Issue by Nathanoid** [cdig/svg-activity-components#28]
I have a couple of buttons on a panel. The visibility of the panel is toggled by a separate button. Now the buttons on the panel have three visible states. To do this I actually made three separate symbols and just cycle through each ones visibility. The problem I'm having is this, if I click on one of the buttons on the panel I am explicitly telling one of its internal symbols to be visible. Then if I click the button to make the whole panel not visible everything disappears except the button symbol that was clicked. So now theres just the button visible. Floating alone in the void.

**Comment by theseanzo** [comment]
Oh weeeeeird. Okay, I'll fix this. Thanks. What seems to happen is that when the visibility is set on children element's, the parent's visibility is no longer inherited. Easy fix.

**Comment by ivyreese** [comment]
Nice! AFAIK, `opacity: 0` and `visibility: hidden` have the same perf characteristics, so this should be just fine from that angle.

:cake:

**Comment by ivyreese** [comment]
(I fucking love that cake)
