### ISSUE TITLE
Have to manually refresh gulp when a change is made in the html

### ISSUE THREAD

**Issue by Nathanoid** [cdig/svg-activity-components#36]
Having to manually refresh gulp when a change is made in the html, while not the end of the world, is easy to forget to do. This ends with my trying to debug a problem when the issue is just that gulp has not updated. If it's possible to have gulp update when the html file is saved like it does with coffee that'd be appreciated. (Not sure if this is the right area for this issue.)

**Comment by ivyreese** [comment]
This was a bug. Cause has been found.
