### ISSUE TITLE
Ability to apply hydraulic pressure color to strokes/lines

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#39]
We need to have the ability to change the color of lines and fills. Currently, strokes must be turned into fills in the FLA to work in the SVG.

**Comment by ivyreese** [comment]
Just splitting hairs — I don't think this is a bug. It might be a shortcoming of the current system, but it's not something that _should_ be working but isn't. It's something that the current system is incapable of, and this is known and intentional.

Unless I'm mistaken :stuck_out_tongue:

**Comment by ivyreese** [comment]
Done
