### ISSUE TITLE
Positioning text with cd-map slow - drag too fast and label gets left behind

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#42]
We had this issue in cd-modules before. Not sure what it was, but it's doing it in svg activities now. "editable" now works, just the labels seem to get left behind if you drag too fast, yet sticks to the mouse, and you have to click to release it.

**Comment by ivyreese** [comment]
This one is tricky. It might take a while before we can fix it. Sorry.

**Comment by ivyreese** [comment]
N/A — Text will be native inside the SVG now
