### ISSUE TITLE
Need to restart gulp to compile changes to SCSS

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#43]
Every change I make to a standalone scss file, I have to quit gulp and restart in order to see the changes.

**Comment by ivyreese** [comment]
Is this the `activity/activity.scss` or the `standalone/styles.scss` or both?

**Comment by crystalrubik** [comment]
In the `standalone/activity.scss` ... Haven't ever used scss in an activity yet.

**Comment by ivyreese** [comment]
I'm going to take a guess that Sean's just-deployed update should fix this.

**Comment by theseanzo** [comment]
Fixed.
