### ISSUE TITLE
Place stageNav controls in center of page

### ISSUE THREAD

**Issue by theseanzo** [cdig/svg-activity-components#50]
currently the stageNav controls aren't in the centre of the SVG and this looks sloppy at certain sizes, even leading to parts of the top to go off screen.

**Comment by ivyreese** [comment]
I think we should probably remove these controls entirely. The more I think about it, the more a pinch/scroll-to-zoom and click/tap-and-drag interface would be better and more intuitive. The current Nav UI predates ubiquitous touch interfaces. People are used to navigating maps using touch — we should borrow that input paradigm.

**Comment by ivyreese** [comment]
Done.
