### ISSUE TITLE
Add default mouse behaviour in Joystick, Slider and Crank

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#56]
Add default mouse behaviour for all interactive SVG Components. 

For example:

`#joystick {
  user-select: none;
  cursor: pointer;
  touch-action: none;
}`

**Comment by crystalrubik** [comment]
And to add to this default mouse behaviour, can we have them reset in schematic mode? Make them return to original position, output 0, and no pointer (if this is all possible)

Thanks!

**Comment by ivyreese** [comment]
To be clear — by "no pointer" Crystal means `cursor: default`, not `cursor: none`.

**Comment by ivyreese** [comment]
N/A — We're doing a new style of component where this sort of behaviour is the responsibility of the component developer (probably... TBD)
