### ISSUE TITLE
Need ability to release outside of interactive components

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#57]
We need a way to release outside of buttons. How do we do this?

**Comment by ivyreese** [comment]
Just to clarify — you need the ability to detect when something was released outside (eg: a "releaseOutside" event)? Or you need a click to succeed even when released outside (eg: "I don't care if the release is inside or outside")?

**Comment by crystalrubik** [comment]
Nathan says the first one.

**Comment by ivyreese** [comment]
Can I get an example of how this might be used?

Don't forget, we didn't have a "releaseOutside" event in AS3 either.

**Comment by Nathanoid** [comment]
Let's say for example I have a button that is active as long as the mouse is down. When you release the mouse while still on the button then the proper mouse up code runs and the button is no longer active. But if you have moved the mouse off of the button when you release then the mouse up code never runs, the button remains active, all kinds of wacky bugs ensue. In AS3 this was done by adding mouse up  listener to the stage itself.

ie:
 `stage.addEventListener(MouseEvent.MOUSE_UP, _onReleaseOutSide);`

**Comment by ivyreese** [comment]
Yep. The solution in JS is to add the mouse up listener to the window.

Using PointerInput, you'd say:

``` coffee
PointerInput.addUp(window, mouseUpHandler)
```

In vanilla coffeescript, you'd say:

``` coffee
window.addEventListener("mouseup", mouseUpHandler)
```

Let me know if that doesn't work. If it does work, you can close the issue :)

**Comment by Nathanoid** [comment]
`PointerInput.addUp(window, mouseUpHandler)` didn't work.

Nor did the other style.

**Comment by theseanzo** [comment]
on an SVG it'll have to be the root element and not the window, as the "window" event doesn't get fired because you're inside an object

**Comment by ivyreese** [comment]
N/A. Content devs will no longer be managing event handling — that's a concern for Component devs, and components will be reviewed for best practices.
