### ISSUE TITLE
Lato added to activity.scss by default

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/svg-activity-components#59]
Could the @font-face scss for lato be available to svg activities by default? (possibly by just changing the starter pkg to already have the code in activity.scss?) Since it's the font we've all agreed to use in our animations, it would make sense not to have to put the scss in every time.

**Comment by ivyreese** [comment]
@theseanzo I would add this, but I'm not sure where or how is the right way to do it. Here's the file to draw "inspiration" (read: copy-paste) from: https://github.com/cdig/cd-module-starter/blob/v2/dist/source/styles/fonts.scss

**Comment by ivyreese** [comment]
This is N/A now. Lato is included as part of the framework.
