### ISSUE TITLE
Green Highlight Color Adjustment 

### ISSUE THREAD

**Issue by theseanzo** [cdig/svg-activity-components#7]
From Crystal:

"Can we tweak the color a bit on the green highlight code to be more like it was in Flash? It washes out the details a bit too much in the new SVG highlight code.

The old Flash highlight didn't work on black, so it took some extra work and invisible symbols... so if we can find a way that addresses both these issues that would be great!"

**Comment by ivyreese** [comment]
The green highlight is deprecated.
